# Generated by Django 3.1.1 on 2021-02-19 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(verbose_name='Created at')),
                ('workout_type', models.CharField(max_length=20)),
            ],
        ),
    ]
