# Generated by Django 3.1.6 on 2021-02-19 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210218_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainees',
            name='created_at',
        ),
    ]
