# Generated by Django 3.1.7 on 2021-02-20 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
